In [1]:
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize

corpus = 'GeeksforGeeks is not a wesbite or a company. GeeksforGeeks is a coding environment. Thats what i love. which is good. Not bad at all'

In [2]:
corpus

'GeeksforGeeks is not a wesbite or a company. GeeksforGeeks is a coding environment. Thats what i love. which is good. Not bad at all'

In [3]:
word_tokenize(corpus)

['GeeksforGeeks',
 'is',
 'not',
 'a',
 'wesbite',
 'or',
 'a',
 'company',
 '.',
 'GeeksforGeeks',
 'is',
 'a',
 'coding',
 'environment',
 '.',
 'Thats',
 'what',
 'i',
 'love',
 '.',
 'which',
 'is',
 'good',
 '.',
 'Not',
 'bad',
 'at',
 'all']

# Finding the Sequence

In [4]:
sequence = []
for word in word_tokenize(corpus):
    if (word != '.'):
        sequence.append(word)

In [5]:
seq = list(set(sequence))

In [6]:
len(seq)

19

In [7]:
sent_tokenize(corpus)

['GeeksforGeeks is not a wesbite or a company.',
 'GeeksforGeeks is a coding environment.',
 'Thats what i love.',
 'which is good.',
 'Not bad at all']

# Finding the Index to Encode

In [8]:
data = []

for sent in sent_tokenize(corpus):
    index = []
    for word in word_tokenize(sent):
        if (word != '.'):
            index.append(seq.index(word))
    data.append(index)

In [9]:
data

[[2, 6, 5, 9, 3, 10, 9, 11],
 [2, 6, 9, 4, 12],
 [16, 18, 8, 1],
 [7, 6, 17],
 [15, 0, 13, 14]]

# Encode the sentences in one hot encoding

# an example
### [0, 1, 2, 3, 4, 5, 3, 7]
### [1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0] ='GeeksforGeeks is not a wesbite or a company'

In [10]:
encoder = [0 for x in range(len(seq))]

In [11]:
encoder

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [12]:
new = []

for indexes in data:
    encoder = [0 for x in range(len(seq))]
    for index in indexes:
        encoder[index] = 1 #whatever numbers we are having in data in each sentences we replace with one (1)
    new.append(encoder)

In [13]:
new

[[0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0]]

# Creating DataFrame

In [14]:
df = pd.DataFrame(new, columns = seq)

In [15]:
df['Sentences_'] = sent_tokenize(corpus)

In [16]:
df

bad  love  GeeksforGeeks  wesbite  coding  not  is  which  i  a  or  \
0    0     0              1        1       0    1   1      0  0  1   1   
1    0     0              1        0       1    0   1      0  0  1   0   
2    0     1              0        0       0    0   0      0  1  0   0   
3    0     0              0        0       0    0   1      1  0  0   0   
4    1     0              0        0       0    0   0      0  0  0   0   

   company  environment  at  all  Not  Thats  good  what  \
0        1            0   0    0    0      0     0     0   
1        0            1   0    0    0      0     0     0   
2        0            0   0    0    0      1     0     1   
3        0            0   0    0    0      0     1     0   
4        0            0   1    1    1      0     0     0   

                                     Sentences_  
0  GeeksforGeeks is not a wesbite or a company.  
1        GeeksforGeeks is a coding environment.  
2                            Thats what i love.  
3                                which is good.  
4                                Not bad at all

# 1)The problem with this is 

#### ['This' ,'is', 'not', 'good', 'at' , 'all']
#### ==>1)'This is good, not bad at all' ==> [1,1,1,1,1,1]
#### ==>2)'This is bad, not good at all' ==> [1,1,1,1,1,1]#the two sentences are completely oppostie but they show same 


# 2) Second Problem it works well with small datasets only not with large datasets

# 2)One hot Encoding with sklearn

#### 1)one word at a time

In [1]:
import pandas as pd
text = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog']
data = pd.get_dummies(text)

In [2]:
data

bird    cat    dog   fish
0  False   True  False  False
1  False  False   True  False
2  False  False  False   True
3   True  False  False  False
4  False   True  False  False
5  False  False   True  False

In [3]:
print(data)
print('-' * 30)
print(data.keys())

    bird    cat    dog   fish
0  False   True  False  False
1  False  False   True  False
2  False  False  False   True
3   True  False  False  False
4  False   True  False  False
5  False  False   True  False
------------------------------
Index(['bird', 'cat', 'dog', 'fish'], dtype='object')


#### 2)Whole sentence at a time

In [5]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']

text = np.array(text)
print(text.shape)

text = np.reshape(text, (-1,1))
print(text.shape)

encoder = OneHotEncoder()
encoder.fit(text)

(4,)
(4, 1)


OneHotEncoder()

In [9]:
one_hot = encoder.transform(text)
print(one_hot.toarray())
print([i[3:] for i in encoder.get_feature_names_out()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['i hate cats', 'i like turtles', 'i love dogs', 'i love the dogs']


#### 3)Tokenized Sentences

In [10]:
from sklearn.preprocessing import OneHotEncoder

text = [['this', 'is', 'good'], ['but','its','fine']]

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

In [11]:
one_hot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (2, 6)>

In [12]:
one_hot.data

array([1., 1., 1., 1., 1., 1.])

In [16]:
print(one_hot.toarray())
print('-'*30)
print([i[3:] for i in encoder.get_feature_names_out()])

[[0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]]
------------------------------
['but', 'this', 'is', 'its', 'fine', 'good']


In [17]:
pd.DataFrame(one_hot.toarray(), columns = [i[3:] for i in encoder.get_feature_names_out()])

but  this   is  its  fine  good
0  0.0   1.0  1.0  0.0   0.0   1.0
1  1.0   0.0  0.0  1.0   1.0   0.0